import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class ProductService {
  products = [
    {
      id: '4',
      title: 'Dumbells',
      price: '35',
      quantity: '1',
      image: 'g1.jpg',
      category: '4',
    },
    {
      id: '5',
      title: 'Protein',
      price: '50',
      quantity: '1',
      image: 'g2.jpg',
      category: '4',
    },
    {
      id: '6',
      title: 'Full Machine',
      price: '60',
      quantity: '1',
      image: 'g3.jpg',
      category: '4',
    },
    {
      id: '7',
      title: 'Back Machine',
      price: '40',
      quantity: '1',
      image: 'g4.jpg',
      category: '4',
    },
    {
      id: '8',
      title: 'Weights',
      price: '70',
      quantity: '1',
      image: 'g5.jpg',
      category: '4',
    },
    {
      id: '9',
      title: 'Weights and Bench',
      price: '80',
      quantity: '1',
      image: 'g6.jpg',
      category: '4',
    },
    {
      id: '1',
      title: 'Candies',
      price: '10',
      quantity: '1',
      image: 'm1.jpg',
      category: '3',
    },

    {
      id: '3',
      title: 'Chips Package',
      price: '30',
      quantity: '1',
      image: 'm3.jpg',
      category: '3',
    },
    {
      id: '10',
      title: 'Fridge',
      price: '240',
      quantity: '1',
      image: 'fridge.jpg',
      category: '1',
    },
    {
      id: '11',
      title: 'Freezer',
      price: '300',
      quantity: '1',
      image: 'freezer.jpg',
      category: '1',
    },
    {
      id: '12',
      title: 'Washing Machine',
      price: '30',
      quantity: '1',
      image: 'washing.jpg',
      category: '1',
    },
    {
      id: '13',
      title: 'Oven',
      price: '180',
      quantity: '1',
      image: 'oven.jpg',
      category: '1',
    },
    {
      id: '14',
      title: 'Meat',
      price: '17',
      quantity: '1',
      image: 'meat.jpg',
      category: '3',
    },
    {
      id: '15',
      title: 'Chicken',
      price: '12',
      quantity: '1',
      image: 'chicken.jpg',
      category: '3',
    },
    {
      id: '16',
      title: 'Penne Pasta',
      price: '5',
      quantity: '1',
      image: 'penne.jpg',
      category: '3',
    },
    {
      id: '17',
      title: 'White Rice',
      price: '11',
      quantity: '1',
      image: 'rice.jpg',
      category: '3',
    },
    {
      id: '18',
      title: 'Black Top',
      price: '15',
      quantity: '1',
      image: 'top.jpg',
      category: '2',
    },
    {
      id: '19',
      title: 'Black Jeans',
      price: '15',
      quantity: '1',
      image: 'pants.jpg',
      category: '2',
    },
    {
      id: '20',
      title: 'Shoes',
      price: '45',
      quantity: '1',
      image: 'shoes.jpg',
      category: '2',
    },
    {
      id: '21',
      title: 'Flower Dress',
      price: '85',
      quantity: '1',
      image: 'dress.jpg',
      category: '2',
    },
    {
      id: '22',
      title: "Men's Underwear",
      price: '15',
      quantity: '1',
      image: 'underwear.jpg',
      category: '2',
    },
  ];
  constructor() {}
  getProducts() {
    return this.products;
  }
}
